### Домашнее задание к уроку 1
**Задание 1**

In [2]:
import numpy as np
# Создадим двумерный массив из 5ти строк и 2ух столбцов
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
# вычислим среднее значение по каждому столбцу и запишем ссылку на итог в переменную mean_a
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

**Задание 2**

In [5]:
#  Вычислим из массива "а" массив mean_a используя Broadcasting и запишем результат в переменную a_centered
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

**Задание 3**

In [10]:
# массив a_centered имеет 5 строк и 2 столбца. для скалярного произведения столбцов, разделим массив по
# столбцам используя срезы
a_centered1 = a_centered[:, 0].copy()
a_centered2 = a_centered[:, 1].copy()

# Теперь можем получить скалярное произведение
a_centered_sp = np.dot(a_centered1, a_centered2)

# Из условия задачи 1: число наблюдений - число строк. Число строк в каждом массиве a_centered1 = 5. (5-1=4 по условию)
a_centered_sp / 4

2.0

**Задание 4**

In [11]:
# для ковариации необходима транпонированная матрица
at = a.transpose()
at

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [16]:
# Далее вычислим ковариацию от транспонрированной матрицы. 
cov_a = np.cov(at)
print(cov_a)

# элемент cov_a[0][1] - будет значением ковариации
first_cov_val = a_centered_sp / 4
second_cov_val = cov_a[0][1]
first_cov_val == second_cov_val

[[1.  2. ]
 [2.  4.3]]


True

**PANDAS**
**Задание 1**

In [17]:
import pandas as pd # импортируем библиотеку Pandas
authors = pd.DataFrame({"authors_id": [1, 2, 3],
                        "authors_name": ["Тургенев", "Чехов", "Островский"]}, 
                       columns=["authors_id", "authors_name"]) # создали датафрейм authors
authors

authors_id authors_name
0           1     Тургенев
1           2        Чехов
2           3   Островский

In [19]:
book = pd.DataFrame({"authors_id": [1, 1, 1, 2, 2, 3, 3],
                     "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 
                                    'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 
                                    'Таланты и поклонники'],
                     "price": [450, 300, 350, 500, 450, 370, 290]},
                    columns=["authors_id", "book_title", "price"])
book

authors_id            book_title  price
0           1           Отцы и дети    450
1           1                 Рудин    300
2           1     Дворянское гнездо    350
3           2      Толстый и тонкий    500
4           2       Дама с собачкой    450
5           3                 Гроза    370
6           3  Таланты и поклонники    290

**Задание 2**

In [22]:
# соединим данные в общую таблицу при помощи pd.merge указав общее поле authors_id
authors_price = pd.merge(authors, book, on="authors_id", how="outer")
authors_price

authors_id authors_name            book_title  price
0           1     Тургенев           Отцы и дети    450
1           1     Тургенев                 Рудин    300
2           1     Тургенев     Дворянское гнездо    350
3           2        Чехов      Толстый и тонкий    500
4           2        Чехов       Дама с собачкой    450
5           3   Островский                 Гроза    370
6           3   Островский  Таланты и поклонники    290

**Задание 3**

In [23]:
# Выберем топ5 самых дорогих книг из датафрейма author_price
top5 = authors_price.nlargest(5, "price")
# перезапустим индексы и удалим старые
top5 = top5.reset_index(drop=True)
top5

authors_id authors_name         book_title  price
0           2        Чехов   Толстый и тонкий    500
1           1     Тургенев        Отцы и дети    450
2           2        Чехов    Дама с собачкой    450
3           3   Островский              Гроза    370
4           1     Тургенев  Дворянское гнездо    350

**Задание 4**

In [60]:
# создадим для каждого минимума, максимума и средней цены свой датафрейм, сгруппировав по "authors_name"
group_max_price = authors_price.groupby("authors_name")["price"].max()
group_min_price = authors_price.groupby("authors_name")["price"].min()
group_mean_price = authors_price.groupby("authors_name")["price"].mean()

In [70]:
# Соединяем все датафреймы в один общий, по общему столбцу "authors_name"
authors_stat = pd.merge(group_max_price, group_min_price, on="authors_name", how="outer")
authors_stat = pd.merge(authors_stat, group_mean_price, on="authors_name", how="outer")
# Переименовываем названия столбцов
authors_stat = authors_stat.rename(columns={"price_x": "max_price", "price_y": "min_price", 
                                           "price": "mean_price"})
# И выделяем индекс
authors_stat.reset_index(inplace=True)
authors_stat

authors_name  max_price  min_price  mean_price
0   Островский        370        290  330.000000
1     Тургенев        450        300  366.666667
2        Чехов        500        450  475.000000

**Задание 5**

In [71]:
# Создадим новый столбец и заполним его данными
authors_price["cover"] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

authors_id authors_name            book_title  price    cover
0           1     Тургенев           Отцы и дети    450  твердая
1           1     Тургенев                 Рудин    300   мягкая
2           1     Тургенев     Дворянское гнездо    350   мягкая
3           2        Чехов      Толстый и тонкий    500  твердая
4           2        Чехов       Дама с собачкой    450  твердая
5           3   Островский                 Гроза    370   мягкая
6           3   Островский  Таланты и поклонники    290   мягкая